controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
        type: attribute

# Je définis la route pour lister toutes les ressources
resource_link_index:
    path: /resources
    controller: App\Controller\ResourceLinkController::index
    methods: [GET]
    # J'ajoute cette route pour permettre d'afficher la page des ressources

# Je définis la route pour afficher le formulaire de création d'une nouvelle ressource
resource_link_create:
    path: /resources/create
    controller: App\Controller\ResourceLinkController::create
    methods: [GET, POST]
    # Cette route gère à la fois l'affichage du formulaire et la soumission des données

# Je définis la route pour afficher le formulaire de modification d'une ressource existante
resource_link_edit:
    path: /resources/edit/{id}
    controller: App\Controller\ResourceLinkController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'
    # Cette route nécessite un paramètre 'id' qui doit être un nombre. Elle gère l'affichage et la mise à jour des informations d'une ressource spécifique.

# Je définis la route pour afficher tous les posts
social_feed_index:
    path: /social-feed
    controller: App\Controller\SocialFeedController::index
    methods: [GET]

# Je définis la route pour ajouter un nouveau post
social_feed_create:
    path: /social-feed/new
    controller: App\Controller\SocialFeedController::create
    methods: [GET, POST]

# Je définis la route pour éditer un post existant
social_feed_edit:
    path: /social-feed/edit/{id}
    controller: App\Controller\SocialFeedController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

# config/routes.yaml
# Routes pour la gestion des documents d'aide

help_index:
    path: /help
    controller: App\Controller\HelpController::index
    methods: GET
    # Je crée une route pour lister tous les documents d'aide disponibles.

help_view:
    path: /help/view/{id}
    controller: App\Controller\HelpController::view
    methods: GET
    requirements:
        id: '\d+'
    # Je crée une route pour afficher un document d'aide spécifique.

help_create:
    path: /help/create
    controller: App\Controller\HelpController::create
    methods: [GET, POST]
    # Je crée une route pour ajouter un nouveau document d'aide.

help_edit:
    path: /help/edit/{id}
    controller: App\Controller\HelpController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'
    # Je crée une route pour éditer un document d'aide existant.

help_delete:
    path: /help/delete/{id}
    controller: App\Controller\HelpController::delete
    methods: DELETE
    requirements:
        id: '\d+'
    # Je crée une route pour supprimer un document d'aide. La méthode DELETE est utilisée pour renforcer la sémantique de l'action.
    # Ces routes assurent une gestion complète des documents d'aide, de la création à la suppression.

app_notre_solution:
    path: /notre-solution
    controller: App\Controller\SolutionController::index

app_history:
    path: /notre-histoire
    controller: App\Controller\HistoryController::index

app_values:
    path: /valeurs
    controller: App\Controller\ValuesController::index